StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65A937B69E902C83}" {
   Id "TurnSignals-Keybind_HazardLights"
   Target_en_us "Hazard lights"
   Target_fr_fr "Feux de détresse"
   Target_it_it "Luci di emergenza"
   Target_de_de "Warnblinker"
   Target_es_es "Luces de emergencia"
   Target_cs_cz "Vvýstražná světla"
   Target_pl_pl "Światła awaryjne"
   Target_ru_ru "Аварийный сигнал"
   Target_ja_jp "ハザードランプ"
   Target_ko_kr "비상등"
   Target_pt_br "Pisca alerta"
   Target_zh_cn "警示灯"
   Target_uk_ua "Аварійні вогні"
   ActorGender NONE
   Status TRANSLATION_DONE
   Modified 1664675426
   Author "Kompoman32"
   LastChanged "Kompoman32"
   Labels {
    409
   }
  }
  CustomStringTableItem "{65A937B69F232988}" {
   Id "TurnSignals-Keybind_LeftSignal"
   Target_en_us "Left signal"
   Target_fr_fr "Clignotant gauche"
   Target_it_it "Freccia sinistra"
   Target_de_de "Blinker links"
   Target_es_es "Intermitente izquierdo"
   Target_cs_cz "Levý blinkr"
   Target_pl_pl "Lewy kierunkowskaz"
   Target_ru_ru "Сигнал левого поворота"
   Target_ja_jp "左のシグナル"
   Target_ko_kr "좌촉방향저시등"
   Target_pt_br "Sinal esquerdo"
   Target_zh_cn "左转信号灯"
   Target_uk_ua "Сигнал лівого повороту"
   Status TRANSLATION_DONE
   Modified 1664675427
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65A937B69DD682D2}" {
   Id "TurnSignals-Keybind_RightSignal"
   Target_en_us "Right signal"
   Target_fr_fr "Clignotant droite"
   Target_it_it "Freccia destra"
   Target_de_de "Blinker rechts"
   Target_es_es "Intermitente derecho"
   Target_cs_cz "Pravý blinkr"
   Target_pl_pl "Prawy kierunkowskaz"
   Target_ru_ru "Сигнал правого поворота"
   Target_ja_jp "右のシグナル"
   Target_ko_kr "오촉방향저시등"
   Target_pt_br "Sinal direito"
   Target_zh_cn "右转信号灯"
   Target_uk_ua "Сигнал правого повороту"
   Status TRANSLATION_DONE
   Modified 1664675429
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
 }
}