StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{68EE33C60D9603F2}" {
   Id "RT-Face_Context_Action_Description"
   Target_en_us "Change face of this unit"
   Modified 1760443129
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{68EE33C1F939FA7F}" {
   Id "RT-Face_Context_Action_Name"
   Target_en_us "Change face"
   Modified 1760443108
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{6610C43CC58AAC5D}" {
   Id "RT-Face_Wardrobe"
   Target_en_us "Faces Wardrobe"
   Modified 1712383962
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{6610C43AFEBC752F}" {
   Id "RT-Face_Wardrobe_Action"
   Target_en_us "Change Face"
   Modified 1712384944
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{68ECC34BA721F377}" {
   Id "RT-Face_Wardrobe_Action_Dialog_Already_Opened"
   Target_en_us "Dialog window already opened"
   Modified 1760351181
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{68ECC34B0777EA91}" {
   Id "RT-Face_Wardrobe_Action_No_Faction"
   Target_en_us "No affiliated faction (try respawn as real player)"
   Modified 1760351022
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{68ECC34B08AB5369}" {
   Id "RT-Face_Wardrobe_Action_No_PlayerController"
   Target_en_us "Non player unit"
   Modified 1760350920
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097435}" {
   Id "RT_Head_AfricanHead_01"
   Target_en_us "Williams"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762421699
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F535AD18E7}" {
   Id "RT_Head_AfricanHead_01_camo"
   Target_en_us "Williams (camo)"
   Modified 1762429189
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C3709741B}" {
   Id "RT_Head_AfricanHead_02"
   Target_en_us "Hasan"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762421705
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F53355E891}" {
   Id "RT_Head_AfricanHead_02_camo"
   Target_en_us "Hasan (Camo)"
   Modified 1762429199
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097442}" {
   Id "RT_Head_AfricanHead_03"
   Target_en_us "Jesus"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762421709
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F531B80094}" {
   Id "RT_Head_AfricanHead_03_camo"
   Target_en_us "Jesus (Camo)"
   Modified 1762429209
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370977FA}" {
   Id "RT_Head_AfricanHead_H"
   Target_en_us "African H"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423536
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F53D8D8ED9}" {
   Id "RT_Head_AfricanHead_h_camo"
   Target_en_us "African H (Camo)"
   Modified 1762429166
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4A800E3846E70}" {
   Id "RT_Head_Asian_02"
   Target_en_us "Reforger Asian"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762428683
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F7F8CC989F}" {
   Id "RT_Head_Asian_02_camo"
   Target_en_us "Reforger Asian (Camo)"
   Modified 1762428855
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A3A9A0B0A83}" {
   Id "RT_Head_Asian_02_VN"
   Target_en_us "Asian (VN)"
   Modified 1762422042
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A3A87B19AC9}" {
   Id "RT_Head_AsianHead_02"
   Target_en_us "Asian"
   Modified 1762422018
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370974A8}" {
   Id "RT_Head_AsianHead_A3_01"
   Target_en_us "Ximi"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422094
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F55CF391A4}" {
   Id "RT_Head_AsianHead_A3_01_camo"
   Target_en_us "Ximi (Camo)"
   Modified 1762429250
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A3AB85599E1}" {
   Id "RT_Head_AsianHead_A3_01_VN"
   Target_en_us "Ximi (VN)"
   Modified 1762422101
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097491}" {
   Id "RT_Head_AsianHead_A3_02"
   Target_en_us "Jeong"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422112
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F55B294089}" {
   Id "RT_Head_AsianHead_A3_02_camo"
   Target_en_us "Jeong (Camo)"
   Modified 1762429257
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A3ACB31B496}" {
   Id "RT_Head_AsianHead_A3_02_VN"
   Target_en_us "Jeong (VN)"
   Modified 1762422131
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370974F9}" {
   Id "RT_Head_AsianHead_A3_03"
   Target_en_us "Tung"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422139
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F55639FC36}" {
   Id "RT_Head_AsianHead_A3_03_camo"
   Target_en_us "Tung (Camo)"
   Modified 1762429262
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A3ADDBA2AD4}" {
   Id "RT_Head_AsianHead_A3_03_VN"
   Target_en_us "Tung (VN)"
   Modified 1762422150
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097524}" {
   Id "RT_Head_AsianHead_A3_04"
   Target_en_us "Lee"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422157
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F39D9065B0}" {
   Id "RT_Head_AsianHead_A3_04_AR"
   Target_en_us "Lee (AR)"
   Modified 1762430255
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F5540DFFA8}" {
   Id "RT_Head_AsianHead_A3_04_camo"
   Target_en_us "Lee (Camo)"
   Modified 1762429267
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A3AD44CA84D}" {
   Id "RT_Head_AsianHead_A3_04_VN"
   Target_en_us "Lee (VN)"
   Modified 1762422162
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097513}" {
   Id "RT_Head_AsianHead_A3_05"
   Target_en_us "Chan"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422168
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F55252714E}" {
   Id "RT_Head_AsianHead_A3_05_camo"
   Target_en_us "Chan (Camo)"
   Modified 1762429275
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A3AEF53F511}" {
   Id "RT_Head_AsianHead_A3_05_VN"
   Target_en_us "Chan (VN)"
   Modified 1762422177
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C3709757C}" {
   Id "RT_Head_AsianHead_A3_06"
   Target_en_us "Yeung"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422185
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3976B261B}" {
   Id "RT_Head_AsianHead_A3_06_AR"
   Target_en_us "Yeung (AR)"
   Modified 1762430263
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F55049E9AC}" {
   Id "RT_Head_AsianHead_A3_06_camo"
   Target_en_us "Yeung (Camo)"
   Modified 1762429280
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A3AE522270A}" {
   Id "RT_Head_AsianHead_A3_06_VN"
   Target_en_us "Yeung (VN)"
   Modified 1762422193
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370975A4}" {
   Id "RT_Head_AsianHead_A3_07"
   Target_en_us "Wong"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422198
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F56E27C665}" {
   Id "RT_Head_AsianHead_A3_07_camo"
   Target_en_us "Wong (Camo)"
   Modified 1762429287
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A3AFD3E584D}" {
   Id "RT_Head_AsianHead_A3_07_VN"
   Target_en_us "Wong (VN)"
   Modified 1762422209
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370975F2}" {
   Id "RT_Head_Barklem"
   Target_en_us "Barklem"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F58FD57393}" {
   Id "RT_Head_Barklem_camo"
   Target_en_us "Barklem (Camo)"
   Modified 1762429303
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4A800E7EA6EEC}" {
   Id "RT_Head_BaseBody_01"
   Target_en_us "BaseBody 01"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800EEF86460}" {
   Id "RT_Head_Black_02"
   Target_en_us "Reforger Black"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762428692
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F7EA72AA7B}" {
   Id "RT_Head_Black_02_camo"
   Target_en_us "Reforger Black (Camo)"
   Modified 1762428695
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097233}" {
   Id "RT_Head_Capek"
   Target_en_us "Capek"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F588129475}" {
   Id "RT_Head_Capek_camo"
   Target_en_us "Capek (Camo)"
   Modified 1762429334
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097269}" {
   Id "RT_Head_Dillon"
   Target_en_us "Dillon"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F594E7D304}" {
   Id "RT_Head_Dillon_camo"
   Target_en_us "Dillon (Camo)"
   Modified 1762429347
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370976F0}" {
   Id "RT_Head_Dwarden"
   Target_en_us "Dwarden"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F6FF157E80}" {
   Id "RT_Head_Dwarden_camo"
   Target_en_us "Dwarden (Camo)"
   Modified 1762429047
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097C5E}" {
   Id "RT_Head_GreekHead_A3_01"
   Target_en_us "Athanasiadis"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422307
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4BEF1C396}" {
   Id "RT_Head_GreekHead_A3_01_camo"
   Target_en_us "Athanasiadis (Camo)"
   Modified 1762429896
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097C88}" {
   Id "RT_Head_GreekHead_A3_02"
   Target_en_us "Baros"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422319
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4BBA2D848}" {
   Id "RT_Head_GreekHead_A3_02_camo"
   Target_en_us "Baros (Camo)"
   Modified 1762429901
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097CC0}" {
   Id "RT_Head_GreekHead_A3_03"
   Target_en_us "Constantinou"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422323
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4B83E2915}" {
   Id "RT_Head_GreekHead_A3_03_camo"
   Target_en_us "Constantinou (Camo)"
   Modified 1762429906
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097D29}" {
   Id "RT_Head_GreekHead_A3_04"
   Target_en_us "Costas"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422326
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4B78F707C}" {
   Id "RT_Head_GreekHead_A3_04_camo"
   Target_en_us "Costas (Camo)"
   Modified 1762429914
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097D0D}" {
   Id "RT_Head_GreekHead_A3_11"
   Target_en_us "Gavras"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422344
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4B517E950}" {
   Id "RT_Head_GreekHead_A3_11_camo"
   Target_en_us "Gavras (Camo)"
   Modified 1762429922
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097D75}" {
   Id "RT_Head_GreekHead_A3_12"
   Target_en_us "Markos"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422348
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4B39043B5}" {
   Id "RT_Head_GreekHead_A3_12_camo"
   Target_en_us "Markos (Camo)"
   Modified 1762429929
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097D58}" {
   Id "RT_Head_GreekHead_A3_13"
   Target_en_us "Alexis"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422353
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4B1120FE7}" {
   Id "RT_Head_GreekHead_A3_13_camo"
   Target_en_us "Alexis (Camo)"
   Modified 1762429933
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097DBF}" {
   Id "RT_Head_GreekHead_A3_14"
   Target_en_us "Dimitrou"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422356
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4CF33E130}" {
   Id "RT_Head_GreekHead_A3_14_camo"
   Target_en_us "Dimitrou (Camo)"
   Modified 1762429939
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370976D6}" {
   Id "RT_Head_Hladas"
   Target_en_us "Hladas"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F1B2CB4013}" {
   Id "RT_Head_Hladas_AR"
   Target_en_us "Hladas (AR)"
   Modified 1762431502
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F500C36D06}" {
   Id "RT_Head_Hladas_camo"
   Target_en_us "Hladas (Camo)"
   Modified 1762429096
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370972A0}" {
   Id "RT_Head_Homewood"
   Target_en_us "Homewood"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5A95BB1FD}" {
   Id "RT_Head_Homewood_camo"
   Target_en_us "Homewood (Camo)"
   Modified 1762429376
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097C73}" {
   Id "RT_Head_IG_Leader"
   Target_en_us "IG Leader"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F383219ED9}" {
   Id "RT_Head_IG_leader_AR"
   Target_en_us "IG Leader (AR)"
   Modified 1762430245
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F4A9698122}" {
   Id "RT_Head_IG_leader_camo"
   Target_en_us "IG Leader (Camo)"
   Modified 1762429834
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097B7F}" {
   Id "RT_Head_Ioannou"
   Target_en_us "Ioannou"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3CA9C64B9}" {
   Id "RT_Head_Ioannou_AR"
   Target_en_us "Ioannou (AR)"
   Modified 1762430343
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F3220BEA37}" {
   Id "RT_Head_Ioannou_camo"
   Target_en_us "Ioannou (Camo)"
   Modified 1762430070
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097710}" {
   Id "RT_Head_Ivan"
   Target_en_us "Ivan"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F37CE8A012}" {
   Id "RT_Head_Ivan_AR"
   Target_en_us "Ivan (AR)"
   Modified 1762430211
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F51A892C7D}" {
   Id "RT_Head_Ivan_camo"
   Target_en_us "Ivan (Camo)"
   Modified 1762429109
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C3709777A}" {
   Id "RT_Head_Jay"
   Target_en_us "Jay"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F38E80C8C9}" {
   Id "RT_Head_Jay_AR"
   Target_en_us "Jay (AR)"
   Modified 1762430219
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F515AF1A7E}" {
   Id "RT_Head_Jay_camo"
   Target_en_us "Jay (Camo)"
   Modified 1762429126
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C3709768D}" {
   Id "RT_Head_Kerry_A"
   Target_en_us "Kerry"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422439
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F6E5DC4448}" {
   Id "RT_Head_Kerry_A_camo"
   Target_en_us "Kerry (Camo)"
   Modified 1762429034
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370972F5}" {
   Id "RT_Head_Kesson"
   Target_en_us "Kesson"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5A3F2920F}" {
   Id "RT_Head_Kesson_camo"
   Target_en_us "Kesson (Camo)"
   Modified 1762429386
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F35F85333A}" {
   Id "RT_Head_Kesson_UK"
   Target_en_us "Kesson (UK)"
   Modified 1762430145
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C3709797F}" {
   Id "RT_Head_Kingsly"
   Target_en_us "Kingsly"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3C7BE95C3}" {
   Id "RT_Head_Kingsly_AR"
   Target_en_us "Kingsly (AR)"
   Modified 1762431143
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F2FCA878E0}" {
   Id "RT_Head_Kingsly_camo"
   Target_en_us "Kingsly (Camo)"
   Modified 1762431139
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370979A3}" {
   Id "RT_Head_Kruglikov"
   Target_en_us "Kruglikov"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F2F5213D9A}" {
   Id "RT_Head_Kruglikov_camo"
   Target_en_us "Kruglikov (Camo)"
   Modified 1762431155
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097DE9}" {
   Id "RT_Head_LivonianHead_1"
   Target_en_us "Nowak"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422455
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097B14}" {
   Id "RT_Head_LivonianHead_10"
   Target_en_us "Rabinowicz"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422465
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3B0BAE260}" {
   Id "RT_Head_LivonianHead_10_AR"
   Target_en_us "Rabinowicz (AR)"
   Modified 1762430330
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F3095E4123}" {
   Id "RT_Head_LivonianHead_10_camo"
   Target_en_us "Rabinowicz (Camo)"
   Modified 1762430003
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F4E2A4901A}" {
   Id "RT_Head_LivonianHead_1_camo"
   Target_en_us "Nowak (Camo)"
   Modified 1762429969
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097DD8}" {
   Id "RT_Head_LivonianHead_2"
   Target_en_us "Górecki"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422471
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3AAE45C43}" {
   Id "RT_Head_LivonianHead_2_AR"
   Target_en_us "Górecki (AR)"
   Modified 1762430304
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F4F2A60CE4}" {
   Id "RT_Head_LivonianHead_2_camo"
   Target_en_us "Górecki (Camo)"
   Modified 1762430008
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097A01}" {
   Id "RT_Head_LivonianHead_3"
   Target_en_us "Kowalski"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422477
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4F33B0DD0}" {
   Id "RT_Head_LivonianHead_3_camo"
   Target_en_us "Kowalski (Camo)"
   Modified 1762430021
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097A65}" {
   Id "RT_Head_LivonianHead_4"
   Target_en_us "Stolarski"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422481
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4F1EF4F08}" {
   Id "RT_Head_LivonianHead_4_camo"
   Target_en_us "Stolarski (Camo)"
   Modified 1762430026
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097A48}" {
   Id "RT_Head_LivonianHead_5"
   Target_en_us "Burak"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422485
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F30E9C033F}" {
   Id "RT_Head_LivonianHead_5_camo"
   Target_en_us "Burak (Cmo)"
   Modified 1762430036
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097AAE}" {
   Id "RT_Head_LivonianHead_6"
   Target_en_us "Kawa"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422488
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F30F6EE3FA}" {
   Id "RT_Head_LivonianHead_6_camo"
   Target_en_us "Kawa (Camo)"
   Modified 1762430041
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097A97}" {
   Id "RT_Head_LivonianHead_7"
   Target_en_us "Janowski"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422493
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F30DD3006D}" {
   Id "RT_Head_LivonianHead_7_camo"
   Target_en_us "Janowski (Camo)"
   Modified 1762430046
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097AFB}" {
   Id "RT_Head_LivonianHead_8"
   Target_en_us "Sternik"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422496
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3BAF42B91}" {
   Id "RT_Head_LivonianHead_8_AR"
   Target_en_us "Sternik (AR)"
   Modified 1762430311
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F30A42EDB8}" {
   Id "RT_Head_LivonianHead_8_camo"
   Target_en_us "Sternik (Camo)"
   Modified 1762430051
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097B27}" {
   Id "RT_Head_LivonianHead_9"
   Target_en_us "Zieliński"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422500
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3B75C0E95}" {
   Id "RT_Head_LivonianHead_9_AR"
   Target_en_us "Zieliński (AR)"
   Modified 1762430321
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F30B160799}" {
   Id "RT_Head_LivonianHead_9_camo"
   Target_en_us "Zieliński (Camo)"
   Modified 1762430057
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097B8F}" {
   Id "RT_Head_Mavros"
   Target_en_us "Mavros"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3DC7135F2}" {
   Id "RT_Head_Mavros_AR"
   Target_en_us "Mavros (AR)"
   Modified 1762430368
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F334BB464F}" {
   Id "RT_Head_Mavros_camo"
   Target_en_us "Mavros (Camo)"
   Modified 1762430096
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097657}" {
   Id "RT_Head_Miller"
   Target_en_us "Miller"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F6DCB91D1C}" {
   Id "RT_Head_Miller_camo"
   Target_en_us "Miller (camo)"
   Modified 1762429009
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097C0C}" {
   Id "RT_Head_Nikos"
   Target_en_us "Nikos"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4AF4E279D}" {
   Id "RT_Head_Nikos_camo"
   Target_en_us "Nikos (Camo)"
   Modified 1762429825
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097311}" {
   Id "RT_Head_Old_Man"
   Target_en_us "Old Man"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5B2765968}" {
   Id "RT_Head_Old_man_camo"
   Target_en_us "Old Man (Camo)"
   Modified 1762429412
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370978CB}" {
   Id "RT_Head_Persian_01"
   Target_en_us "Bahadur"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422820
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F2168A838F}" {
   Id "RT_Head_Persian_01_camo"
   Target_en_us "Bahadur (Camo)"
   Modified 1762430533
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097930}" {
   Id "RT_Head_Persian_02"
   Target_en_us "Jalali"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422826
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F2143C48CB}" {
   Id "RT_Head_Persian_02_camo"
   Target_en_us "Jalali (Camo)"
   Modified 1762430538
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097914}" {
   Id "RT_Head_Persian_03"
   Target_en_us "Sabet"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422830
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F2159DA35A}" {
   Id "RT_Head_Persian_03_camo"
   Target_en_us "Sabet (Camo)"
   Modified 1762430587
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370977A0}" {
   Id "RT_Head_Pettka"
   Target_en_us "Pettka"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F38A49E411}" {
   Id "RT_Head_Pettka_AR"
   Target_en_us "Pettka (AR)"
   Modified 1762430233
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F52C1C1706}" {
   Id "RT_Head_Pettka_camo"
   Target_en_us "Pettka (Camo)"
   Modified 1762429143
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097788}" {
   Id "RT_Head_Player"
   Target_en_us "Player"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5221ACD01}" {
   Id "RT_Head_Player_camo"
   Target_en_us "Player (Camo)"
   Modified 1762429154
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097BAA}" {
   Id "RT_Head_Rudwell"
   Target_en_us "Rudwell"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F33A97CEC3}" {
   Id "RT_Head_Rudwell_camo"
   Target_en_us "Rudwell (Camo)"
   Modified 1762430086
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097810}" {
   Id "RT_Head_RussianHead_1"
   Target_en_us "Ivanov"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422866
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3F9DE0E87}" {
   Id "RT_Head_RussianHead_1_camo"
   Target_en_us "Ivanov (Camo)"
   Modified 1762430438
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097875}" {
   Id "RT_Head_RussianHead_2"
   Target_en_us "Petrenko"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422871
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F20EC2BADE}" {
   Id "RT_Head_RussianHead_2_camo"
   Target_en_us "Petrenko (Camo)"
   Modified 1762430482
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097859}" {
   Id "RT_Head_RussianHead_3"
   Target_en_us "Krupin"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422874
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F20F587836}" {
   Id "RT_Head_RussianHead_3_camo"
   Target_en_us "Krupin (Camo)"
   Modified 1762430457
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370978BC}" {
   Id "RT_Head_RussianHead_4"
   Target_en_us "Adamovich"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422877
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F20DCF5C96}" {
   Id "RT_Head_RussianHead_4_camo"
   Target_en_us "Adamovich (Camo)"
   Modified 1762430469
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370978E4}" {
   Id "RT_Head_RussianHead_5"
   Target_en_us "Yakhin"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422881
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F20D40FFBB}" {
   Id "RT_Head_RussianHead_5_camo"
   Target_en_us "Yakhin (Camo)"
   Modified 1762430476
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C3709782B}" {
   Id "RT_Head_Smolko"
   Target_en_us "Smolko"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3D6D17D60}" {
   Id "RT_Head_Smolko_AR"
   Target_en_us "Smolko (AR)"
   Modified 1762430376
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F3481FF2ED}" {
   Id "RT_Head_Smolko_camo"
   Target_en_us "Smolko (Camo)"
   Modified 1762430117
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097324}" {
   Id "RT_Head_Sturrock"
   Target_en_us "Sturrock"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5BD7FED4F}" {
   Id "RT_Head_Sturrock_camo"
   Target_en_us "Sturrock (Camo)"
   Modified 1762429402
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097BF6}" {
   Id "RT_Head_Stype"
   Target_en_us "Stype"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F34EFDCCBC}" {
   Id "RT_Head_Stype_camo"
   Target_en_us "Stype (Camo)"
   Modified 1762430106
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370973A5}" {
   Id "RT_Head_Tanoan_01"
   Target_en_us "Simo"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422913
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5C6ACA72D}" {
   Id "RT_Head_Tanoan_01_camo"
   Target_en_us "Simo (Camo)"
   Modified 1762429461
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C3709738E}" {
   Id "RT_Head_Tanoan_02"
   Target_en_us "Adnet"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422916
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5C455138D}" {
   Id "RT_Head_Tanoan_02_camo"
   Target_en_us "Adnet (Camo)"
   Modified 1762429469
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370973F4}" {
   Id "RT_Head_Tanoan_03"
   Target_en_us "Cahun"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422919
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5C2083D07}" {
   Id "RT_Head_Tanoan_03_camo"
   Target_en_us "Cahun (Camo)"
   Modified 1762429473
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370973DB}" {
   Id "RT_Head_Tanoan_04"
   Target_en_us "Ganio"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422922
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5C0E4850C}" {
   Id "RT_Head_Tanoan_04_camo"
   Target_en_us "Ganio (Camo)"
   Modified 1762429482
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C3709703A}" {
   Id "RT_Head_Tanoan_05"
   Target_en_us "Malet"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422925
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5C14012FA}" {
   Id "RT_Head_Tanoan_05_camo"
   Target_en_us "Malet (Camo)"
   Modified 1762429488
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097061}" {
   Id "RT_Head_Tanoan_06"
   Target_en_us "Solé"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422928
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5DFF1CF7E}" {
   Id "RT_Head_Tanoan_06_camo"
   Target_en_us "Solé (Camo)"
   Modified 1762429493
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097045}" {
   Id "RT_Head_Tanoan_07"
   Target_en_us "Mignard"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422932
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5DC008675}" {
   Id "RT_Head_Tanoan_07_camo"
   Target_en_us "Mignard (Camo)"
   Modified 1762429499
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370970AB}" {
   Id "RT_Head_Tanoan_08"
   Target_en_us "Thibaud"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422935
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5DA7ADA13}" {
   Id "RT_Head_Tanoan_08_camo"
   Target_en_us "Thibaud (Camo)"
   Modified 1762429508
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097379}" {
   Id "RT_Head_Tanoan_Boss"
   Target_en_us "Solomon Maru"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422943
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F5CC601F44}" {
   Id "RT_Head_Tanoan_Boss_camo"
   Target_en_us "Solomon Maru (Camo)"
   Modified 1762429422
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4A8028CD00245}" {
   Id "RT_Head_White_02"
   Target_en_us "Reforger White 02"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762428804
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F662BF9976}" {
   Id "RT_Head_White_02_camo_USSR_01"
   Target_en_us "Reforger White 02 USSR (Camo)"
   Modified 1762428816
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4A800DED42FC9}" {
   Id "RT_Head_White_03"
   Target_en_us "Reforger White 03"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423588
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F7F29557B2}" {
   Id "RT_Head_White_03_camo"
   Target_en_us "Reforger White 03 (Camo)"
   Modified 1762428623
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4A800FD02464A}" {
   Id "RT_Head_White_04"
   Target_en_us "Reforger White 04"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423592
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F694C49FC4}" {
   Id "RT_Head_White_04_camo"
   Target_en_us "Reforger White 04 (Camo)"
   Modified 1762428891
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4A800FA21F88B}" {
   Id "RT_Head_White_05"
   Target_en_us "Reforger White 05"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423595
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F6904475F1}" {
   Id "RT_Head_White_05_camo"
   Target_en_us "Reforger White 05 (Camo)"
   Modified 1762428897
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4A800F8361D8D}" {
   Id "RT_Head_White_06"
   Target_en_us "Reforger White 06"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423598
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F6A8399A04}" {
   Id "RT_Head_White_06_camo"
   Target_en_us "Reforger White 06 (Camo)"
   Modified 1762428913
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F6A24CD9F6}" {
   Id "RT_Head_White_07_camo"
   Target_en_us "Reforger White 07 (Camo)"
   Modified 1762428920
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4A800F7AE41C8}" {
   Id "RT_Head_White_08"
   Target_en_us "Reforger White 08"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423600
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F6B477B75A}" {
   Id "RT_Head_White_08_camo"
   Target_en_us "Reforger White 08 (Camo)"
   Modified 1762428949
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4A800F424188E}" {
   Id "RT_Head_White_09"
   Target_en_us "Reforger White 09"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423604
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F6CD5324AF}" {
   Id "RT_Head_White_09_camo"
   Target_en_us "Reforger White 09 (Camo)"
   Modified 1762428968
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4A800F273D7F8}" {
   Id "RT_Head_White_10"
   Target_en_us "Reforger White 10"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423606
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F6C27F34BB}" {
   Id "RT_Head_White_10_camo"
   Target_en_us "Reforger White 10 (Camo)"
   Modified 1762428980
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C3709708E}" {
   Id "RT_Head_WhiteHead_01"
   Target_en_us "Bayh"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422985
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F41CBD2B7A}" {
   Id "RT_Head_WhiteHead_01_camo"
   Target_en_us "Bayh (Camo)"
   Modified 1762429648
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A38EE9C7A61}" {
   Id "RT_Head_WhiteHead_01_VN"
   Target_en_us "Bayh (VN)"
   Modified 1762423342
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370970F4}" {
   Id "RT_Head_WhiteHead_02"
   Target_en_us "Burr"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422988
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F418A48A44}" {
   Id "RT_Head_WhiteHead_02_camo"
   Target_en_us "Burr (Camo)"
   Modified 1762429653
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A38D4449759}" {
   Id "RT_Head_WhiteHead_02_VN"
   Target_en_us "Burr (VN)"
   Modified 1762423333
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370970DD}" {
   Id "RT_Head_WhiteHead_03"
   Target_en_us "Coburn"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422991
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4169474D4}" {
   Id "RT_Head_WhiteHead_03_camo"
   Target_en_us "Coburn (Camo)"
   Modified 1762429658
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097102}" {
   Id "RT_Head_WhiteHead_04"
   Target_en_us "Collins"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422994
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4175DD361}" {
   Id "RT_Head_WhiteHead_04_camo"
   Target_en_us "Collins (Camo)"
   Modified 1762429665
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C3709716D}" {
   Id "RT_Head_WhiteHead_05"
   Target_en_us "Campbell"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762422997
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F41418793E}" {
   Id "RT_Head_WhiteHead_05_camo"
   Target_en_us "Campbell (Camo)"
   Modified 1762429671
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F352F51608}" {
   Id "RT_Head_WhiteHead_05_UK"
   Target_en_us "Campbell (UK)"
   Modified 1762430158
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A38DD55CD4A}" {
   Id "RT_Head_WhiteHead_05_VN"
   Target_en_us "Campbell (VN)"
   Modified 1762423321
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097155}" {
   Id "RT_Head_WhiteHead_06"
   Target_en_us "Dayton"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423000
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F412A39C5E}" {
   Id "RT_Head_WhiteHead_06_camo"
   Target_en_us "Dayton (Camo)"
   Modified 1762429678
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370971BE}" {
   Id "RT_Head_WhiteHead_07"
   Target_en_us "Dorgan"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423004
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4131AE980}" {
   Id "RT_Head_WhiteHead_07_camo"
   Target_en_us "Dorgan (Camo)"
   Modified 1762429683
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370971E6}" {
   Id "RT_Head_WhiteHead_08"
   Target_en_us "Halliwell"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423007
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F390A202D8}" {
   Id "RT_Head_WhiteHead_08_AR"
   Target_en_us "Halliwell (AR)"
   Modified 1762430276
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F411BCA144}" {
   Id "RT_Head_WhiteHead_08_camo"
   Target_en_us "Halliwell (Camo)"
   Modified 1762429688
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A38C963B179}" {
   Id "RT_Head_WhiteHead_08_VN"
   Target_en_us "Halliwell (VN)"
   Modified 1762423305
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C370971DF}" {
   Id "RT_Head_WhiteHead_09"
   Target_en_us "Johnson"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423010
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F42F54F8F3}" {
   Id "RT_Head_WhiteHead_09_camo"
   Target_en_us "Johnson (Camo)"
   Modified 1762429697
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097E04}" {
   Id "RT_Head_WhiteHead_10"
   Target_en_us "Martinez"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423014
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F42D238038}" {
   Id "RT_Head_WhiteHead_10_camo"
   Target_en_us "Martinez (Camo)"
   Modified 1762429703
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A38B28EB963}" {
   Id "RT_Head_WhiteHead_10_VN"
   Target_en_us "Martinez (VN)"
   Modified 1762423281
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097E69}" {
   Id "RT_Head_WhiteHead_11"
   Target_en_us "Kirby"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423017
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F427DB82A0}" {
   Id "RT_Head_WhiteHead_11_camo"
   Target_en_us "Kirby (Camo)"
   Modified 1762429710
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F36C519897}" {
   Id "RT_Head_WhiteHead_11_UK"
   Target_en_us "Kirby (UK)"
   Modified 1762430169
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A38BDC8D81B}" {
   Id "RT_Head_WhiteHead_11_VN"
   Target_en_us "Kirby (VN)"
   Modified 1762423265
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097E4A}" {
   Id "RT_Head_WhiteHead_12"
   Target_en_us "Reed"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423021
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F425DA56F8}" {
   Id "RT_Head_WhiteHead_12_camo"
   Target_en_us "Reed (Camo)"
   Modified 1762429715
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097EAF}" {
   Id "RT_Head_WhiteHead_13"
   Target_en_us "Santorum"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423029
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F422A09AF8}" {
   Id "RT_Head_WhiteHead_13_camo"
   Target_en_us "Santorum (Camo)"
   Modified 1762429721
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097E94}" {
   Id "RT_Head_WhiteHead_14"
   Target_en_us "Smith"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423034
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F4218E8C25}" {
   Id "RT_Head_WhiteHead_14_camo"
   Target_en_us "Smith (Camo)"
   Modified 1762429726
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097EF6}" {
   Id "RT_Head_WhiteHead_15"
   Target_en_us "Snowe"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423041
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F43E45EC69}" {
   Id "RT_Head_WhiteHead_15_camo"
   Target_en_us "Snowe (Camo)"
   Modified 1762429731
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F362060423}" {
   Id "RT_Head_WhiteHead_15_UK"
   Target_en_us "Snowe (UK)"
   Modified 1762430184
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A38A83F7C03}" {
   Id "RT_Head_WhiteHead_15_VN"
   Target_en_us "Snowe (VN)"
   Modified 1762423246
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097EDB}" {
   Id "RT_Head_WhiteHead_16"
   Target_en_us "Kelly"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423044
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F43F3A853D}" {
   Id "RT_Head_WhiteHead_16_camo"
   Target_en_us "Kelly (Camo)"
   Modified 1762429738
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C6A38920B487A}" {
   Id "RT_Head_WhiteHead_16_VN"
   Target_en_us "Kelly (VN)"
   Modified 1762423224
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097F3C}" {
   Id "RT_Head_WhiteHead_17"
   Target_en_us "O'Connor"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423049
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3D22837D7}" {
   Id "RT_Head_WhiteHead_17_AR"
   Target_en_us "O'Connor (AR)"
   Modified 1762430385
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F43A826137}" {
   Id "RT_Head_WhiteHead_17_camo"
   Target_en_us "O'Connor (Camo)"
   Modified 1762429747
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097F1F}" {
   Id "RT_Head_WhiteHead_18"
   Target_en_us "Byrne"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423074
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3ECBAB396}" {
   Id "RT_Head_WhiteHead_18_AR"
   Target_en_us "Byrne (AR)"
   Modified 1762430393
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F43B26A891}" {
   Id "RT_Head_WhiteHead_18_camo"
   Target_en_us "Byrne (Camo)"
   Modified 1762429778
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097F43}" {
   Id "RT_Head_WhiteHead_19"
   Target_en_us "O'Brien"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423070
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F43992F30F}" {
   Id "RT_Head_WhiteHead_19_camo"
   Target_en_us "O'Brien (Camo)"
   Modified 1762429785
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097FA9}" {
   Id "RT_Head_WhiteHead_20"
   Target_en_us "Walsh"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423080
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3E976FE01}" {
   Id "RT_Head_WhiteHead_20_AR"
   Target_en_us "Walsh (AR)"
   Modified 1762430406
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F4379442EB}" {
   Id "RT_Head_WhiteHead_20_camo"
   Target_en_us "Walsh (Camo)"
   Modified 1762429790
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097F93}" {
   Id "RT_Head_WhiteHead_21"
   Target_en_us "O'Sullivan"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423084
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3E3E9C5EA}" {
   Id "RT_Head_WhiteHead_21_AR"
   Target_en_us "O'Sullivan (AR)"
   Modified 1762430416
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F43407EAC8}" {
   Id "RT_Head_WhiteHead_21_camo"
   Target_en_us "O'Sullivan (Camo)"
   Modified 1762429797
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097FF9}" {
   Id "RT_Head_WhiteHead_22"
   Target_en_us "Kirby"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1762423093
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{690C84F3FCFC2FEC}" {
   Id "RT_Head_WhiteHead_22_AR"
   Target_en_us "Kirby (AR)"
   Modified 1762430423
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{690C84F4334F1846}" {
   Id "RT_Head_WhiteHead_22_camo"
   Target_en_us "Kirby (Camo)"
   Modified 1762429802
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
 }
}