StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6610C43CC58AAC5D}" {
   Id "RT-Face_Wardrobe"
   Target_en_us "Faces Wardrobe"
   Modified 1712383962
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{6610C43AFEBC752F}" {
   Id "RT-Face_Wardrobe_Action"
   Target_en_us "Change Face"
   Modified 1712384944
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65D4ED3C37097435}" {
   Id "RT_Head_AfricanHead_01"
   Target_en_us "AfricanHead 01"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709741B}" {
   Id "RT_Head_AfricanHead_02"
   Target_en_us "AfricanHead 02"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097442}" {
   Id "RT_Head_AfricanHead_03"
   Target_en_us "AfricanHead 03"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370977FA}" {
   Id "RT_Head_AfricanHead_H"
   Target_en_us "AfricanHead H"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800E3846E70}" {
   Id "RT_Head_Asian_02"
   Target_en_us "Asian 02"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370974A8}" {
   Id "RT_Head_AsianHead_A3_01"
   Target_en_us "AsianHead A3 01"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097491}" {
   Id "RT_Head_AsianHead_A3_02"
   Target_en_us "AsianHead A3 02"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370974F9}" {
   Id "RT_Head_AsianHead_A3_03"
   Target_en_us "AsianHead A3 03"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097524}" {
   Id "RT_Head_AsianHead_A3_04"
   Target_en_us "AsianHead A3 04"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097513}" {
   Id "RT_Head_AsianHead_A3_05"
   Target_en_us "AsianHead A3 05"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709757C}" {
   Id "RT_Head_AsianHead_A3_06"
   Target_en_us "AsianHead A3 06"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370975A4}" {
   Id "RT_Head_AsianHead_A3_07"
   Target_en_us "AsianHead A3 07"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370975F2}" {
   Id "RT_Head_Barklem"
   Target_en_us "Barklem"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800E7EA6EEC}" {
   Id "RT_Head_BaseBody_01"
   Target_en_us "BaseBody 01"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800EEF86460}" {
   Id "RT_Head_Black_02"
   Target_en_us "Black 02"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097233}" {
   Id "RT_Head_Capek"
   Target_en_us "Capek"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097269}" {
   Id "RT_Head_Dillon"
   Target_en_us "Dillon"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370976F0}" {
   Id "RT_Head_Dwarden"
   Target_en_us "Dwarden"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097C5E}" {
   Id "RT_Head_GreekHead_A3_01"
   Target_en_us "GreekHead A3 01"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097C88}" {
   Id "RT_Head_GreekHead_A3_02"
   Target_en_us "GreekHead A3 02"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097CC0}" {
   Id "RT_Head_GreekHead_A3_03"
   Target_en_us "GreekHead A3 03"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097D29}" {
   Id "RT_Head_GreekHead_A3_04"
   Target_en_us "GreekHead A3 04"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097D0D}" {
   Id "RT_Head_GreekHead_A3_11"
   Target_en_us "GreekHead A3 11"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097D75}" {
   Id "RT_Head_GreekHead_A3_12"
   Target_en_us "GreekHead A3 12"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097D58}" {
   Id "RT_Head_GreekHead_A3_13"
   Target_en_us "GreekHead A3 13"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097DBF}" {
   Id "RT_Head_GreekHead_A3_14"
   Target_en_us "GreekHead A3 14"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370976D6}" {
   Id "RT_Head_Hladas"
   Target_en_us "Hladas"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370972A0}" {
   Id "RT_Head_Homewood"
   Target_en_us "Homewood"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097C73}" {
   Id "RT_Head_IG_Leader"
   Target_en_us "IG Leader"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097B7F}" {
   Id "RT_Head_Ioannou"
   Target_en_us "Ioannou"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097710}" {
   Id "RT_Head_Ivan"
   Target_en_us "Ivan"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709777A}" {
   Id "RT_Head_Jay"
   Target_en_us "Jay"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709768D}" {
   Id "RT_Head_Kerry_A"
   Target_en_us "Kerry A"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370972F5}" {
   Id "RT_Head_Kesson"
   Target_en_us "Kesson"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709797F}" {
   Id "RT_Head_Kingsly"
   Target_en_us "Kingsly"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370979A3}" {
   Id "RT_Head_Kruglikov"
   Target_en_us "Kruglikov"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097DE9}" {
   Id "RT_Head_LivonianHead_1"
   Target_en_us "LivonianHead 1"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097B14}" {
   Id "RT_Head_LivonianHead_10"
   Target_en_us "LivonianHead 10"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097DD8}" {
   Id "RT_Head_LivonianHead_2"
   Target_en_us "LivonianHead 2"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097A01}" {
   Id "RT_Head_LivonianHead_3"
   Target_en_us "LivonianHead 3"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097A65}" {
   Id "RT_Head_LivonianHead_4"
   Target_en_us "LivonianHead 4"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097A48}" {
   Id "RT_Head_LivonianHead_5"
   Target_en_us "LivonianHead 5"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097AAE}" {
   Id "RT_Head_LivonianHead_6"
   Target_en_us "LivonianHead 6"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097A97}" {
   Id "RT_Head_LivonianHead_7"
   Target_en_us "LivonianHead 7"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097AFB}" {
   Id "RT_Head_LivonianHead_8"
   Target_en_us "LivonianHead 8"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097B27}" {
   Id "RT_Head_LivonianHead_9"
   Target_en_us "LivonianHead 9"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097B8F}" {
   Id "RT_Head_Mavros"
   Target_en_us "Mavros"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097657}" {
   Id "RT_Head_Miller"
   Target_en_us "Miller"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097C0C}" {
   Id "RT_Head_Nikos"
   Target_en_us "Nikos"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097311}" {
   Id "RT_Head_Old_Man"
   Target_en_us "Old Man"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370978CB}" {
   Id "RT_Head_Persian_01"
   Target_en_us "Persian 01"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097930}" {
   Id "RT_Head_Persian_02"
   Target_en_us "Persian 02"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097914}" {
   Id "RT_Head_Persian_03"
   Target_en_us "Persian 03"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370977A0}" {
   Id "RT_Head_Pettka"
   Target_en_us "Pettka"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097788}" {
   Id "RT_Head_Player"
   Target_en_us "Player"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097BAA}" {
   Id "RT_Head_Rudwell"
   Target_en_us "Rudwell"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097810}" {
   Id "RT_Head_RussianHead_1"
   Target_en_us "RussianHead 1"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097875}" {
   Id "RT_Head_RussianHead_2"
   Target_en_us "RussianHead 2"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097859}" {
   Id "RT_Head_RussianHead_3"
   Target_en_us "RussianHead 3"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370978BC}" {
   Id "RT_Head_RussianHead_4"
   Target_en_us "RussianHead 4"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370978E4}" {
   Id "RT_Head_RussianHead_5"
   Target_en_us "RussianHead 5"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709782B}" {
   Id "RT_Head_Smolko"
   Target_en_us "Smolko"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097324}" {
   Id "RT_Head_Sturrock"
   Target_en_us "Sturrock"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097BF6}" {
   Id "RT_Head_Stype"
   Target_en_us "Stype"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370973A5}" {
   Id "RT_Head_Tanoan_01"
   Target_en_us "Tanoan 01"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709738E}" {
   Id "RT_Head_Tanoan_02"
   Target_en_us "Tanoan 02"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370973F4}" {
   Id "RT_Head_Tanoan_03"
   Target_en_us "Tanoan 03"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370973DB}" {
   Id "RT_Head_Tanoan_04"
   Target_en_us "Tanoan 04"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709703A}" {
   Id "RT_Head_Tanoan_05"
   Target_en_us "Tanoan 05"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097061}" {
   Id "RT_Head_Tanoan_06"
   Target_en_us "Tanoan 06"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097045}" {
   Id "RT_Head_Tanoan_07"
   Target_en_us "Tanoan 07"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370970AB}" {
   Id "RT_Head_Tanoan_08"
   Target_en_us "Tanoan 08"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097379}" {
   Id "RT_Head_Tanoan_Boss"
   Target_en_us "Tanoan Boss"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A8028CD00245}" {
   Id "RT_Head_White_02"
   Target_en_us "White 02"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370979D8}" {
   Id "RT_Head_White_02_Tk"
   Target_en_us "White 02 Tk"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800DED42FC9}" {
   Id "RT_Head_White_03"
   Target_en_us "White 03"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800D9BAD7FD}" {
   Id "RT_Head_White_03_Old"
   Target_en_us "White 02 Old"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370979F4}" {
   Id "RT_Head_White_03_Old_Tk"
   Target_en_us "White 03 Old Tk"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709798F}" {
   Id "RT_Head_White_03_Tk"
   Target_en_us "White 03 Tk"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800FD02464A}" {
   Id "RT_Head_White_04"
   Target_en_us "White 04"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800FA21F88B}" {
   Id "RT_Head_White_05"
   Target_en_us "White 05"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800F8361D8D}" {
   Id "RT_Head_White_06"
   Target_en_us "White 06"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709663F}" {
   Id "RT_Head_White_06_Tk"
   Target_en_us "White 06 Tk"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800F7AE41C8}" {
   Id "RT_Head_White_08"
   Target_en_us "White 08"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709666C}" {
   Id "RT_Head_White_08_Tk"
   Target_en_us "White 08 Tk"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800F424188E}" {
   Id "RT_Head_White_09"
   Target_en_us "White 09"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4A800F273D7F8}" {
   Id "RT_Head_White_10"
   Target_en_us "White 10"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author "Kompoman32"
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709708E}" {
   Id "RT_Head_WhiteHead_01"
   Target_en_us "WhiteHead 01"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370970F4}" {
   Id "RT_Head_WhiteHead_02"
   Target_en_us "WhiteHead 02"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370970DD}" {
   Id "RT_Head_WhiteHead_03"
   Target_en_us "WhiteHead 03"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097102}" {
   Id "RT_Head_WhiteHead_04"
   Target_en_us "WhiteHead 04"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C3709716D}" {
   Id "RT_Head_WhiteHead_05"
   Target_en_us "WhiteHead 05"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097155}" {
   Id "RT_Head_WhiteHead_06"
   Target_en_us "WhiteHead 06"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370971BE}" {
   Id "RT_Head_WhiteHead_07"
   Target_en_us "WhiteHead 07"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370971E6}" {
   Id "RT_Head_WhiteHead_08"
   Target_en_us "WhiteHead 08"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C370971DF}" {
   Id "RT_Head_WhiteHead_09"
   Target_en_us "WhiteHead 09"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097E04}" {
   Id "RT_Head_WhiteHead_10"
   Target_en_us "WhiteHead 10"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097E69}" {
   Id "RT_Head_WhiteHead_11"
   Target_en_us "WhiteHead 11"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097E4A}" {
   Id "RT_Head_WhiteHead_12"
   Target_en_us "WhiteHead 12"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097EAF}" {
   Id "RT_Head_WhiteHead_13"
   Target_en_us "WhiteHead 13"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097E94}" {
   Id "RT_Head_WhiteHead_14"
   Target_en_us "WhiteHead 14"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097EF6}" {
   Id "RT_Head_WhiteHead_15"
   Target_en_us "WhiteHead 15"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097EDB}" {
   Id "RT_Head_WhiteHead_16"
   Target_en_us "WhiteHead 16"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097F3C}" {
   Id "RT_Head_WhiteHead_17"
   Target_en_us "WhiteHead 17"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097F1F}" {
   Id "RT_Head_WhiteHead_18"
   Target_en_us "WhiteHead 18"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097F43}" {
   Id "RT_Head_WhiteHead_19"
   Target_en_us "WhiteHead 19"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097FA9}" {
   Id "RT_Head_WhiteHead_20"
   Target_en_us "WhiteHead 20"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097F93}" {
   Id "RT_Head_WhiteHead_21"
   Target_en_us "WhiteHead 21"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65D4ED3C37097FF9}" {
   Id "RT_Head_WhiteHead_22"
   Target_en_us "WhiteHead 22"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1708455581
   Author ""
   LastChanged "Kompoman32"
   ImageLink ""
   Hidden 0
  }
 }
}