StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{691AC42F9DC2DCA5}" {
   Id "RT_EEI_ContentBrowser_Header_Name"
   Target_en_us "Choose Arsenal"
   Modified 1763363936
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{691AC42F521D8841}" {
   Id "RT_EEI_ContextAction_EditInventory_Description"
   Target_en_us "Choose arsenal and edit inventory of the entity."
   Modified 1763363843
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{691AC42F40AA618A}" {
   Id "RT_EEI_ContextAction_EditInventory_Name"
   Target_en_us "Edit inventory..."
   Modified 1763363819
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{691AC429947A7B82}" {
   Id "RT_EEI_Notification_ACTION_NEED_CONTROLLED_ENTITY"
   Target_en_us "You need to create your player character before you can edit someone's inventory"
   Modified 1763371034
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
 }
}