StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{68605E046DCEFEFD}" {
   Id "RT_II-Prop_Guitar_Name"
   Target_en_us "Guitar"
   Target_ru_ru "Гитара"
   Modified 1751156754
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{68605E047FAB5137}" {
   Id "RT_II-Prop_Organ_Name"
   Target_en_us "Organ"
   Target_ru_ru "Орган"
   Modified 1751156748
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
 }
}