StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{673AD766CCF9FAB7}" {
   Id "RT_WS-MovePoint_Attribute_Radius_Description"
   Target_en_us "Radius of assembly point area"
   Target_ru_ru "Радиус точки сбора"
   Modified 1751938866
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673AD766B2D19DBF}" {
   Id "RT_WS-MovePoint_Attribute_Radius_Name"
   Target_en_us "Radius"
   Target_ru_ru "Радиус"
   Modified 1751938573
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{6846B7EE5F4566E2}" {
   Id "RT_WS-MovePoint_Description"
   Target_en_us "Group of units will go here after spawning"
   Target_ru_ru "Группы юнитов будут двигаться к этой точке"
   Modified 1751938729
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{6846B7EE43AF1289}" {
   Id "RT_WS-MovePoint_Name"
   Target_en_us "Assembly Point"
   Target_ru_ru "Точка сбора"
   Modified 1751938716
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C4FC0F697597EC}" {
   Id "RT_WS-WavesSpawner_Base_Description"
   Target_en_us "Spawner to generate waves of units"
   Target_ru_ru "Спавнер для генерации волн юнитов"
   Modified 1751938680
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C4FC0F6ECF85DC}" {
   Id "RT_WS-WavesSpawner_Base_Name"
   Target_en_us "Waves Spawner"
   Target_ru_ru "Спавнер Волн"
   Modified 1751944681
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7D6E7890D}" {
   Id "RT_WS-WavesSpawner_FIA_Description"
   Target_en_us "Spawner to generate waves of FIA units"
   Target_ru_ru "Спавнер для генерации волн FIA юнитов"
   Modified 1751940008
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7C37A13A4}" {
   Id "RT_WS-WavesSpawner_FIA_Name"
   Target_en_us "FIA Waves Spawner"
   Target_ru_ru "FIA Спавнер Волн"
   Modified 1751944699
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7DA64C3C9}" {
   Id "RT_WS-WavesSpawner_US_Description"
   Target_en_us "Spawner to generate waves of US units"
   Target_ru_ru "Спавнер для генерации волн США юнитов"
   Modified 1751940002
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7C6C8F609}" {
   Id "RT_WS-WavesSpawner_US_Name"
   Target_en_us "US Waves Spawner"
   Target_ru_ru "США Спавнер Волн"
   Modified 1751944689
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7D8EDBBB9}" {
   Id "RT_WS-WavesSpawner_USSR_Description"
   Target_en_us "Spawner to generate waves of USSR units"
   Target_ru_ru "Спавнер для генерации волн СССР юнитов"
   Modified 1751939995
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7C562B0FB}" {
   Id "RT_WS-WavesSpawner_USSR_Name"
   Target_en_us "USSR Waves Spawner"
   Target_ru_ru "СССР Спавнер Волн"
   Modified 1751944692
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F812CCD9BC}" {
   Id "RT_WS-WavesSpawnerAttribute_Delay_Description"
   Target_en_us "Delay between spawns of groups"
   Target_ru_ru "Задержка между спавнами групп"
   Modified 1751938944
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522FBE3ED2B07}" {
   Id "RT_WS-WavesSpawnerAttribute_Delay_Name"
   Target_en_us "Delay"
   Target_ru_ru "Задержка"
   Modified 1751938959
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C674B35D720B11}" {
   Id "RT_WS-WavesSpawnerAttribute_Enabled_Description"
   Target_en_us "Enable this spawner"
   Target_ru_ru "Включить этот спавнер"
   Modified 1751939171
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C674B34541D395}" {
   Id "RT_WS-WavesSpawnerAttribute_Enabled_Name"
   Target_en_us "Enable"
   Target_ru_ru "Включить"
   Modified 1751939162
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F85F265D10}" {
   Id "RT_WS-WavesSpawnerAttribute_MaxEntities_Description"
   Target_en_us "The maximum number of groups that can simultaneously exist linked to this spawner"
   Target_ru_ru "Максимальное количество групп, которые могут одновременно существовать, связанных с этим генератором групп"
   Modified 1751939255
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F8433F85CE}" {
   Id "RT_WS-WavesSpawnerAttribute_MaxEntities_Name"
   Target_en_us "Max groups spawned"
   Target_ru_ru "Максимум групп"
   Modified 1751939336
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673A8E14F8659946}" {
   Id "RT_WS-WavesSpawnerAttribute_MaxInGroup_Description"
   Target_en_us "Max units in one group"
   Target_ru_ru "Максимальное количество юнитов в группе"
   Modified 1751939302
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673A8E14DD3E3F20}" {
   Id "RT_WS-WavesSpawnerAttribute_MaxInGroup_Name"
   Target_en_us "Max units in group"
   Target_ru_ru "Максимум юнитов в группе"
   Modified 1751940071
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673A8E14FAE98FCB}" {
   Id "RT_WS-WavesSpawnerAttribute_MinInGroup_Description"
   Target_en_us "Min units in one group"
   Target_ru_ru "Минимальное количество юнитов в группе"
   Modified 1751948327
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673A8E14D2283768}" {
   Id "RT_WS-WavesSpawnerAttribute_MinInGroup_Name"
   Target_en_us "Min units in group"
   Target_ru_ru "Минимум юнитов в группе"
   Modified 1751949550
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{686C8A025DBCFDA2}" {
   Id "RT_WS-WavesSpawnerAttribute_MinInGroup_Warning_Description"
   Target_en_us "<color rgba=\"226,168,79,255\">Min exceeds the Max.</color> Max number will be applied"
   Target_ru_ru "<color rgba=\"226,168,79,255\">Минимум превышает Максимум.</color> Будет применено Максимальное количество"
   Modified 1751952505
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673AEBD8FE960C76}" {
   Id "RT_WS-WavesSpawnerAttribute_Radius_Description"
   Target_en_us "Radius of spawns of groups <color rgba=\"226,168,79,255\">(group will spawn in a random point in this radius)</color>"
   Target_ru_ru "Радиус спавна групп <color rgba=\"226,168,79,255\">(группа будет заспавнена в случайной точки в пределах радиуса)</color>"
   Modified 1751947431
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673AEBD8E4E15D1A}" {
   Id "RT_WS-WavesSpawnerAttribute_Radius_Name"
   Target_en_us "Spawn Radius"
   Target_ru_ru "Радиус спавна"
   Modified 1751938602
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{686C8A0EDB6B8BC9}" {
   Id "RT_WS-WavesSpawnerAttribute_Units_Description"
   Target_en_us "Adjusting the weights for each type of unit"
   Target_ru_ru "Настройка весов каждого вида юнита"
   Modified 1751946668
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{686C8A0EC791DFB3}" {
   Id "RT_WS-WavesSpawnerAttribute_Units_Name"
   Target_en_us "Units"
   Target_ru_ru "Юниты"
   Modified 1751946630
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
 }
}