StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{673AD766CCF9FAB7}" {
   Id "RT_WS-MovePoint_Attribute_Radius_Description"
   Target_en_us "Radius of assembly point area"
   Modified 1731912395
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673AD766B2D19DBF}" {
   Id "RT_WS-MovePoint_Attribute_Radius_Name"
   Target_en_us "Radius"
   Modified 1731912364
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C4FC0F697597EC}" {
   Id "RT_WS-WavesSpawner_Base_Description"
   Modified 1724186277
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C4FC0F6ECF85DC}" {
   Id "RT_WS-WavesSpawner_Base_Name"
   Target_en_us "Waves Spawner"
   Modified 1724186340
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{6739035836E010A1}" {
   Id "RT_WS-WavesSpawner_FIA_AT"
   Target_en_us "Anti-Tank"
   Modified 1731813050
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7D6E7890D}" {
   Id "RT_WS-WavesSpawner_FIA_Description"
   Modified 1724202180
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673903583CAA356D}" {
   Id "RT_WS-WavesSpawner_FIA_GL"
   Target_en_us "Grenadier"
   Modified 1731813036
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{67390358206096E5}" {
   Id "RT_WS-WavesSpawner_FIA_MG"
   Target_en_us "Machine Gunner"
   Modified 1731813030
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7C37A13A4}" {
   Id "RT_WS-WavesSpawner_FIA_Name"
   Target_en_us "FIA Waves Spawner"
   Modified 1724202188
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{6739035812F215F8}" {
   Id "RT_WS-WavesSpawner_FIA_Rifleman"
   Target_en_us "Rifleman"
   Modified 1731812998
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673903582CE45D2C}" {
   Id "RT_WS-WavesSpawner_FIA_Sniper"
   Target_en_us "Sniper"
   Modified 1731813026
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{6739034791D272D1}" {
   Id "RT_WS-WavesSpawner_US_AT"
   Target_en_us "Anti-Tank"
   Modified 1731813072
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7DA64C3C9}" {
   Id "RT_WS-WavesSpawner_US_Description"
   Modified 1724202170
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{6739034781595CB3}" {
   Id "RT_WS-WavesSpawner_US_GL"
   Target_en_us "Grenadier"
   Modified 1731813068
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{67390347959039F4}" {
   Id "RT_WS-WavesSpawner_US_MG"
   Target_en_us "Machine Gunner"
   Modified 1731813064
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7C6C8F609}" {
   Id "RT_WS-WavesSpawner_US_Name"
   Target_en_us "US Waves Spawner"
   Modified 1724202199
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{67390347765E3919}" {
   Id "RT_WS-WavesSpawner_US_Rifleman"
   Target_en_us "Rifleman"
   Modified 1731812704
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673903477341EFCD}" {
   Id "RT_WS-WavesSpawner_US_Sniper"
   Target_en_us "Sniper"
   Modified 1731812712
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{67390346FCC2DAAC}" {
   Id "RT_WS-WavesSpawner_USSR_AMG"
   Target_en_us "Automatic Machine Gunner"
   Modified 1731812503
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673903470F07F99D}" {
   Id "RT_WS-WavesSpawner_USSR_AT"
   Target_en_us "Anti-Tank"
   Modified 1731812497
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7D8EDBBB9}" {
   Id "RT_WS-WavesSpawner_USSR_Description"
   Modified 1724202176
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{67390346D7D92A3C}" {
   Id "RT_WS-WavesSpawner_USSR_GL"
   Target_en_us "Grenadier"
   Modified 1731812513
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{67390346E7C24040}" {
   Id "RT_WS-WavesSpawner_USSR_MG"
   Target_en_us "Machine Gunner"
   Modified 1731812518
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F7C562B0FB}" {
   Id "RT_WS-WavesSpawner_USSR_Name"
   Target_en_us "USSR Waves Spawner"
   Modified 1724202194
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{67390346B1EE6477}" {
   Id "RT_WS-WavesSpawner_USSR_Rifleman"
   Target_en_us "Rifleman"
   Modified 1731812585
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{67390346C07ED037}" {
   Id "RT_WS-WavesSpawner_USSR_Sniper"
   Target_en_us "Sniper"
   Modified 1731812399
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F812CCD9BC}" {
   Id "RT_WS-WavesSpawnerAttribute_Delay_Description"
   Modified 1724196548
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522FBE3ED2B07}" {
   Id "RT_WS-WavesSpawnerAttribute_Delay_Name"
   Target_en_us "Delay between spawns"
   Modified 1724196582
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C674B35D720B11}" {
   Id "RT_WS-WavesSpawnerAttribute_Enabled_Description"
   Modified 1724283557
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C674B34541D395}" {
   Id "RT_WS-WavesSpawnerAttribute_Enabled_Name"
   Target_en_us "Enabled"
   Modified 1724283548
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F85F265D10}" {
   Id "RT_WS-WavesSpawnerAttribute_MaxEntities_Description"
   Modified 1724196642
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C522F8433F85CE}" {
   Id "RT_WS-WavesSpawnerAttribute_MaxEntities_Name"
   Target_en_us "Max groups spawned"
   Modified 1731895769
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673A8E14F8659946}" {
   Id "RT_WS-WavesSpawnerAttribute_MaxInGroup_Description"
   Modified 1731895792
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673A8E14DD3E3F20}" {
   Id "RT_WS-WavesSpawnerAttribute_MaxInGroup_Name"
   Target_en_us "Max units in group"
   Modified 1731895736
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673A8E14FAE98FCB}" {
   Id "RT_WS-WavesSpawnerAttribute_MinInGroup_Description"
   Modified 1731895787
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673A8E14D2283768}" {
   Id "RT_WS-WavesSpawnerAttribute_MinInGroup_Name"
   Target_en_us "Min units in group"
   Modified 1731895755
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673AEBD8FE960C76}" {
   Id "RT_WS-WavesSpawnerAttribute_Radius_Description"
   Modified 1731915143
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{673AEBD8E4E15D1A}" {
   Id "RT_WS-WavesSpawnerAttribute_Radius_Name"
   Target_en_us "Spawn Radius"
   Modified 1731915138
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
 }
}