// Autogenerated by the Generate Class from Layout plugin v0.5.0
// Layout file: UI/layouts/HUD/StanceInfo/StanceInfo.layout
class SCR_StanceInfoWidgets
{
	protected static const ResourceName LAYOUT = "{D4629479D234F80C}UI/layouts/HUD/StanceInfo/StanceInfo.layout";

	VerticalLayoutWidget m_wStanceInfoPanel;
	HorizontalLayoutWidget m_wStancePosition;
	ImageWidget m_wStance;
	ImageWidget m_wStanceStand;
	ImageWidget m_wStanceCrounch;
	ImageWidget m_wStanceProne;
	FrameWidget m_wSpeedStance;
	ImageWidget m_wStanceSpeed0;
	ImageWidget m_wStanceSpeed1;
	ImageWidget m_wStanceSpeed2;
	ImageWidget m_wStanceSpeed3;
	ImageWidget m_wStanceSpeed4;
	ImageWidget m_wStanceSpeed5;
	ImageWidget m_wStanceSpeed6;
	ImageWidget m_wStanceSpeed7;
	ImageWidget m_wStanceSpeed8;
	ImageWidget m_wStanceSpeed9;

	//------------------------------------------------------------------------------------------------
	bool Init(Widget root)
	{
		m_wStanceInfoPanel = VerticalLayoutWidget.Cast(root.FindAnyWidget("m_StanceInfoPanel"));
		m_wStancePosition = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_StancePosition"));
		m_wStance = ImageWidget.Cast(root.FindAnyWidget("m_Stance"));
		m_wStanceStand = ImageWidget.Cast(root.FindAnyWidget("m_StanceStand"));
		m_wStanceCrounch = ImageWidget.Cast(root.FindAnyWidget("m_StanceCrounch"));
		m_wStanceProne = ImageWidget.Cast(root.FindAnyWidget("m_StanceProne"));
		m_wSpeedStance = FrameWidget.Cast(root.FindAnyWidget("m_SpeedStance"));
		m_wStanceSpeed0 = ImageWidget.Cast(root.FindAnyWidget("m_StanceSpeed0"));
		m_wStanceSpeed1 = ImageWidget.Cast(root.FindAnyWidget("m_StanceSpeed1"));
		m_wStanceSpeed2 = ImageWidget.Cast(root.FindAnyWidget("m_StanceSpeed2"));
		m_wStanceSpeed3 = ImageWidget.Cast(root.FindAnyWidget("m_StanceSpeed3"));
		m_wStanceSpeed4 = ImageWidget.Cast(root.FindAnyWidget("m_StanceSpeed4"));
		m_wStanceSpeed5 = ImageWidget.Cast(root.FindAnyWidget("m_StanceSpeed5"));
		m_wStanceSpeed6 = ImageWidget.Cast(root.FindAnyWidget("m_StanceSpeed6"));
		m_wStanceSpeed7 = ImageWidget.Cast(root.FindAnyWidget("m_StanceSpeed7"));
		m_wStanceSpeed8 = ImageWidget.Cast(root.FindAnyWidget("m_StanceSpeed8"));
		m_wStanceSpeed9 = ImageWidget.Cast(root.FindAnyWidget("m_StanceSpeed9"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
