SCR_NotificationConfig {
 m_aNotificationDisplayData {
  SCR_NotificationDisplayData "{691AC42AB61F228D}" {
   m_NotificationKey ACTION_NEED_CONTROLLED_ENTITY
   m_info SCR_UINotificationInfo "{691AC429038D82AA}" {
    Name "#RT_EEI_Notification_ACTION_NEED_CONTROLLED_ENTITY"
    Icon "{5D9BA0547F2E3804}UI/Textures/Editor/ContextMenu/ContextAction_Control.edds"
    m_cNotificationColor WARNING
   }
  }
 }
}