SCR_EditorActionList {
 m_Actions {
  RT_CF_ChangeFaceContextAction "{68EE33C1D4EB2B44}" {
   m_Info SCR_UIInfo "{68EE33C1EF10FD4C}" {
    Name "#RT-Face_Context_Action_Name"
    Description "#RT-Face_Context_Action_Description"
    Icon "{3262679C50EF4F01}UI/Textures/Icons/icons_wrapperUI.imageset"
    IconSetName "death"
   }
   m_iOrder 233
   m_bEnableShortcutLogics 0
  }
 }
}