SCR_EditorActionList {
 m_Actions {
  RT_WS_AddUnitsToCustomSpawnerContextAction "{68EAABD84003C200}" {
   m_Info SCR_UIInfo "{68EAABD84003B38D}" {
    Name "#RT_WS_ContextAction_AddNearbyUnits_Name"
    Description "#RT_WS_ContextAction_AddNearbyUnits_Description"
    Icon "{3262679C50EF4F01}UI/Textures/Icons/icons_wrapperUI.imageset"
    IconSetName "squad"
   }
   m_iOrder 233
   m_bShowOnCooldownNotification 0
   m_bIsServer 1
  }
 }
}